version: "3.1"

services:
  postgres:
    image: postgres:10
    container_name: clinic_management_db
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - clinic_management:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: clinic_management_redis
    ports:
      - ${REDIS_PORT}:6379
    restart: always

volumes:
  clinic_management:
